---
apiVersion: v1
kind: Service
metadata:
  name: qotm-2
  annotations:
    "consul.hashicorp.com/service-tags": "svc2"
    "consul.hashicorp.com/service-meta-svc": "qotm2"
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  qotm-2_mapping
      prefix: /qotm/
      headers:
        x-dc: "2"
      tls: ambassador-consul
      service: https://qotm-2:443
spec:
  type: NodePort
  selector:
    app: qotm-2
  ports:
  - port: 443
    name: https-qotm
    targetPort: 20000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: qotm-2
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: qotm-2
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
    spec:
      containers:
      - name: qotm
        image: datawire/qotm:svc2
        ports:
        - name: http-api
          containerPort: 5000
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 3
        resources:
          limits:
            cpu: "0.1"
            memory: 100Mi