---
apiVersion: getambassador.io/v1beta1
kind: Middleware
metadata:
  name: param-plugin # how to refer to the plugin in the Policy CRD
  namespace: default
spec:
  Plugin:
    name: param-plugin # The plugin's `.so` file's base name
---
apiVersion: getambassador.io/v1beta1
kind: Policy
metadata:
  name: httpbin-policy
  namespace: default
spec:
  # everything defaults to private; you can create rules to make stuff
  # public, and you can create rules to require additional scopes
  # which will be automatically checked
  rules:
  - host: "*"
    path: /test/*
    public: false # must be false if using a middleware
    middleware:
      name: param-plugin
  - host: "*"
    path: /httpbin/*
    public: false # must be false if using a middleware
    middleware:
      name: param-plugin
  - host: "*"
    path: /qotm/*
    public: false
    middleware:
      name: param-plugin