---
apiVersion: getambassador.io/v1beta2
kind: Filter
metadata:
  name: param-filter # how to refer to the plugin in the Policy CRD
  namespace: default
spec:
  Plugin:
    name: param-plugin # The plugin's `.so` file's base name
---
apiVersion: getambassador.io/v1beta2
kind: FilterPolicy
metadata:
  name: test-filterpolicy
  namespace: default
spec:
  # everything defaults to private; you can create rules to make stuff
  # public, and you can create rules to require additional scopes
  # which will be automatically checked
  rules:
  - host: "*"
    path: /test/*
    filters:
    - name: param-filter
  - host: "*"
    path: /httpbin/*
    filters: null
  - host: "*"
    path: /qotm/*
    filters: null
  - host: "*"
    path: /microdonut/*
    filters: null
  - host: "*"
    path: /zipkin/*
    filters: null
