---
apiVersion: v1
kind: Service
metadata:
  name: compositor
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: compositor
      prefix: /compositor/
      service: compositor
spec:
  type: ClusterIP
  selector:
    service: compositor
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: compositor
  labels:
    service: compositor
spec:
  replicas: 1
  selector:
    matchLabels:
      service: compositor
  template:
    metadata:
      labels:
        service: compositor
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/connect-service-upstreams": "qotm:1234"
    spec:
      containers:
      - name: compositor
        image: quay.io/datawire/compositor:375db06
        env:
        - name: URLS
          value: "http://httpbin.org/stream http://127.0.0.1:1234/quote"
        ports:
        - containerPort: 8080
