---
apiVersion: v1
kind: Service
metadata:
  name: compositor
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: compositor
      prefix: /compositor/
      service: compositor
spec:
  type: ClusterIP
  selector:
    service: compositor
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: compositor
  labels:
    service: compositor
spec:
  replicas: 1
  selector:
    matchLabels:
      service: compositor
  template:
    metadata:
      labels:
        service: compositor
    spec:
      containers:
      - name: compositor
        image: quay.io/datawire/compositor:7c410c9
        ports:
        - containerPort: 8080
