---
apiVersion: v1
kind: Service
metadata:
  name: ws-sync
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  a_ws-mapping
      use_websocket: true
      prefix: /ws_sync/
      service: ws-sync:80
spec:
  selector:
    app: ws-sync
  ports:
  - name: ws-sync
    port: 80
    targetPort: http-server
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ws-sync
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ws-sync
    spec:
      containers:
      - name: ws-sync
        image: "nkrause/ws_sync:v5"
        ports:
        - name: http-server
          containerPort: 4000